/* const data = [
  // Existing products
  {
    id: 1,
    url: "https://img.freepik.com/free-photo/elegant-plants-decoration-vase_23-2149334653.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Elegant Plant Decoration",
    price: 99,
    fakePrice: 129,
    offer: "30%",
    rating: 3.5,
    category: "All Product",
  },
  {
    id: 2,
    url: "https://img.freepik.com/free-photo/still-life-with-indoor-plants_23-2151024959.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Indoor Plant Still Life",
    price: 129,
    fakePrice: 159,
    offer: "36%",
    rating: 4.9,
    category: "All Product",
  },
  {
    id: 3,
    url: "https://img.freepik.com/free-photo/still-life-with-indoor-plants_23-2151024942.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Indoor Plant Decoration",
    price: 115,
    fakePrice: 199,
    offer: "35%",
    rating: 4.3,
    category: "All Product",
  },
  {
    id: 4,
    url: "https://img.freepik.com/free-photo/view-green-palm-tree-species-with-beautiful-foliage_23-2151486605.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Green Palm Tree Species",
    price: 189,
    fakePrice: 299,
    offer: "45%",
    rating: 4.3,
    category: "All Product",
  },
  // Seeds
  {
    id: 5,
    url: "https://img.freepik.com/free-photo/sunflower-seeds-bowl_23-2148334889.jpg",
    name: "Sunflower Seeds Pack",
    price: 59,
    fakePrice: 79,
    offer: "25%",
    rating: 4.7,
    category: "Seeds",
  },
  {
    id: 6,
    url: "https://img.freepik.com/free-photo/poppy-seeds-wooden-bowl_23-2148465198.jpg",
    name: "Poppy Seeds Pack",
    price: 45,
    fakePrice: 60,
    offer: "20%",
    rating: 4.5,
    category: "Seeds",
  },
  {
    id: 7,
    url: "https://img.freepik.com/free-photo/pack-of-vegetable-seeds_23-2148491234.jpg",
    name: "Vegetable Seeds Assortment",
    price: 99,
    fakePrice: 130,
    offer: "24%",
    rating: 4.8,
    category: "Seeds",
  },
  {
    id: 8,
    url: "https://img.freepik.com/free-photo/herb-seeds-variety_23-2148463189.jpg",
    name: "Herb Seeds Variety Pack",
    price: 39,
    fakePrice: 55,
    offer: "29%",
    rating: 4.6,
    category: "Seeds",
  },
  // Flower Bulbs
  {
    id: 9,
    url: "https://img.freepik.com/free-photo/flower-bulbs-scattered_23-2148435602.jpg",
    name: "Tulip Flower Bulbs",
    price: 89,
    fakePrice: 120,
    offer: "26%",
    rating: 4.8,
    category: "Flower Bulbs",
  },
  {
    id: 10,
    url: "https://img.freepik.com/free-photo/colorful-flower-bulbs-arranged_23-2148273589.jpg",
    name: "Daffodil Flower Bulbs",
    price: 75,
    fakePrice: 100,
    offer: "25%",
    rating: 4.6,
    category: "Flower Bulbs",
  },
  {
    id: 11,
    url: "https://img.freepik.com/free-photo/collection-of-lily-flower-bulbs_23-2148274567.jpg",
    name: "Lily Flower Bulbs",
    price: 95,
    fakePrice: 130,
    offer: "27%",
    rating: 4.7,
    category: "Flower Bulbs",
  },
  {
    id: 12,
    url: "https://img.freepik.com/free-photo/rose-flower-bulbs-assorted_23-2148247890.jpg",
    name: "Rose Flower Bulbs",
    price: 85,
    fakePrice: 115,
    offer: "26%",
    rating: 4.5,
    category: "Flower Bulbs",
  },
  // Pots
  {
    id: 13,
    url: "https://img.freepik.com/free-photo/clay-pots-arrangement_23-2148351270.jpg",
    name: "Clay Pot Set",
    price: 40,
    fakePrice: 50,
    offer: "20%",
    rating: 4.2,
    category: "Pots",
  },
  {
    id: 14,
    url: "https://img.freepik.com/free-photo/ceramic-plant-pots_23-2148311247.jpg",
    name: "Ceramic Plant Pot",
    price: 150,
    fakePrice: 180,
    offer: "17%",
    rating: 4.7,
    category: "Pots",
  },
  {
    id: 15,
    url: "https://img.freepik.com/free-photo/metal-garden-pots_23-2148356890.jpg",
    name: "Metal Garden Pots",
    price: 110,
    fakePrice: 145,
    offer: "24%",
    rating: 4.4,
    category: "Pots",
  },
  {
    id: 16,
    url: "https://img.freepik.com/free-photo/terracotta-pots_23-2148384567.jpg",
    name: "Terracotta Pots",
    price: 60,
    fakePrice: 80,
    offer: "25%",
    rating: 4.3,
    category: "Pots",
  },
  // Soil & Fertilizers
  {
    id: 17,
    url: "https://img.freepik.com/free-photo/soil-fertilizer-mix_23-2148234898.jpg",
    name: "Organic Soil Mix",
    price: 35,
    fakePrice: 45,
    offer: "22%",
    rating: 4.4,
    category: "Soil & Fertilizers",
  },
  {
    id: 18,
    url: "https://img.freepik.com/free-photo/garden-fertilizer-bag_23-2148347895.jpg",
    name: "Garden Fertilizer",
    price: 70,
    fakePrice: 95,
    offer: "27%",
    rating: 4.5,
    category: "Soil & Fertilizers",
  },
  {
    id: 19,
    url: "https://img.freepik.com/free-photo/compost-bag-garden-use_23-2148394567.jpg",
    name: "Compost Bag",
    price: 50,
    fakePrice: 70,
    offer: "29%",
    rating: 4.6,
    category: "Soil & Fertilizers",
  },
  {
    id: 20,
    url: "https://img.freepik.com/free-photo/plant-growth-fertilizer_23-2148467890.jpg",
    name: "Plant Growth Fertilizer",
    price: 90,
    fakePrice: 120,
    offer: "25%",
    rating: 4.8,
    category: "Soil & Fertilizers",
  },
  // Pebbles
  {
    id: 21,
    url: "https://img.freepik.com/free-photo/natural-pebbles-collection_23-2148245678.jpg",
    name: "Natural Garden Pebbles",
    price: 30,
    fakePrice: 50,
    offer: "40%",
    rating: 4.0,
    category: "Pebbles",
  },
  {
    id: 22,
    url: "https://img.freepik.com/free-photo/colored-decorative-pebbles_23-2148267895.jpg",
    name: "Colored Decorative Pebbles",
    price: 55,
    fakePrice: 75,
    offer: "27%",
    rating: 4.6,
    category: "Pebbles",
  },
  {
    id: 23,
    url: "https://img.freepik.com/free-photo/smooth-white-pebbles_23-2148367891.jpg",
    name: "Smooth White Pebbles",
    price: 40,
    fakePrice: 60,
    offer: "33%",
    rating: 4.2,
    category: "Pebbles",
  },
  {
    id: 24,
    url: "https://img.freepik.com/free-photo/river-pebbles_23-2148478950.jpg",
    name: "River Pebbles",
    price: 35,
    fakePrice: 55,
    offer: "36%",
    rating: 4.1,
    category: "Pebbles",
  },
  // Gifts
  {
    id: 25,
    url: "https://t4.ftcdn.net/jpg/05/26/89/27/240_F_526892749_TGePASLdg9uihUZtfquZpdGKD8FLTSTF.jpg",
    name: "Plant Gift Box Set",
    price: 120,
    fakePrice: 150,
    offer: "20%",
    rating: 4.8,
    category: "Gifts",
  },
  {
    id: 26,
    url: "https://img.freepik.com/free-photo/mini-garden-kit-gift_23-2148234567.jpg",
    name: "Mini Garden Kit",
    price: 80,
    fakePrice: 100,
    offer: "20%",
    rating: 4.5,
    category: "Gifts",
  },
  {
    id: 27,
    url: "https://img.freepik.com/free-photo/potted-plant-gift_23-2148234578.jpg",
    name: "Potted Plant Gift",
    price: 70,
    fakePrice: 90,
    offer: "22%",
    rating: 4.3,
    category: "Gifts",
  },
  {
    id: 28,
    url: "https://img.freepik.com/free-photo/succulent-gift-box_23-2148234907.jpg",
    name: "Succulent Gift Box",
    price: 60,
    fakePrice: 75,
    offer: "20%",
    rating: 4.4,
    category: "Gifts",
  },
  // Accessories
  {
    id: 29,
    url: "https://img.freepik.com/free-photo/gardening-tool-set_23-2148357890.jpg",
    name: "Gardening Tool Set",
    price: 50,
    fakePrice: 70,
    offer: "29%",
    rating: 4.7,
    category: "Accessories",
  },
  {
    id: 30,
    url: "https://img.freepik.com/free-photo/watering-can-garden-use_23-2148237895.jpg",
    name: "Watering Can",
    price: 25,
    fakePrice: 35,
    offer: "28%",
    rating: 4.4,
    category: "Accessories",
  },
  {
    id: 31,
    url: "https://img.freepik.com/free-photo/garden-gloves-pack_23-2148364567.jpg",
    name: "Garden Gloves Pack",
    price: 15,
    fakePrice: 25,
    offer: "40%",
    rating: 4.2,
    category: "Accessories",
  },
  {
    id: 32,
    url: "https://img.freepik.com/free-photo/plant-labels-tags_23-2148234568.jpg",
    name: "Plant Labels and Tags",
    price: 10,
    fakePrice: 15,
    offer: "33%",
    rating: 4.0,
    category: "Accessories",
  },
  // Offers & Blogs
  {
    id: 33,
    url: "https://img.freepik.com/free-photo/garden-maintenance-tips_23-2148345789.jpg",
    name: "Garden Maintenance Tips",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.9,
    category: "Offers",
  },
  {
    id: 34,
    url: "https://img.freepik.com/free-photo/diy-garden-projects_23-2148234890.jpg",
    name: "DIY Garden Projects",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.8,
    category: "Offers",
  },
  {
    id: 35,
    url: "https://img.freepik.com/free-photo/plants-care-guide_23-2148234789.jpg",
    name: "Plant Care Guide",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 5.0,
    category: "Offers",
  },
  {
    id: 36,
    url: "https://img.freepik.com/free-photo/seasonal-planting-guide_23-2148234568.jpg",
    name: "Seasonal Planting Guide",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.7,
    category: "Offers",
  },
]; */

const data = [
  // Existing products
  {
    id: 1,
    url: "https://img.freepik.com/free-photo/elegant-plants-decoration-vase_23-2149334653.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Elegant Plant Decoration",
    price: 99,
    fakePrice: 129,
    offer: "30%",
    rating: 3.5,
    category: "All Product",
    warranty: "1-year warranty on vase and plant condition.",
    inStock: true,
  },
  {
    id: 2,
    url: "https://img.freepik.com/free-photo/still-life-with-indoor-plants_23-2151024959.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Indoor Plant Still Life",
    price: 129,
    fakePrice: 159,
    offer: "36%",
    rating: 4.9,
    category: "All Product",
    warranty: "6-month warranty on plant health.",
    inStock: true,
  },
  {
    id: 3,
    url: "https://img.freepik.com/free-photo/still-life-with-indoor-plants_23-2151024942.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Indoor Plant Decoration",
    price: 115,
    fakePrice: 199,
    offer: "35%",
    rating: 4.3,
    category: "All Product",
    warranty: "1-year warranty on plant condition.",
    inStock: true,
  },
  {
    id: 4,
    url: "https://img.freepik.com/free-photo/view-green-palm-tree-species-with-beautiful-foliage_23-2151486605.jpg?uid=R154964719&ga=GA1.1.940856582.1720781664&semt=ais_hybrid",
    name: "Green Palm Tree Species",
    price: 189,
    fakePrice: 299,
    offer: "45%",
    rating: 4.3,
    category: "All Product",
    warranty: "1-year warranty for plant and foliage health.",
    inStock: true,
  },
  // Seeds
  {
    id: 5,
    url: "https://img.freepik.com/free-photo/sunflower-seeds-bowl_23-2148334889.jpg",
    name: "Sunflower Seeds Pack",
    price: 59,
    fakePrice: 79,
    offer: "25%",
    rating: 4.7,
    category: "Seeds",
    warranty: "No warranty; seeds are non-returnable.",
    inStock: true,
  },
  {
    id: 6,
    url: "https://img.freepik.com/free-photo/poppy-seeds-wooden-bowl_23-2148465198.jpg",
    name: "Poppy Seeds Pack",
    price: 45,
    fakePrice: 60,
    offer: "20%",
    rating: 4.5,
    category: "Seeds",
    warranty: "No warranty; seeds are non-returnable.",
    inStock: true,
  },
  {
    id: 7,
    url: "https://img.freepik.com/free-photo/pack-of-vegetable-seeds_23-2148491234.jpg",
    name: "Vegetable Seeds Assortment",
    price: 99,
    fakePrice: 130,
    offer: "24%",
    rating: 4.8,
    category: "Seeds",
    warranty: "No warranty; seeds are non-returnable.",
    inStock: true,
  },
  {
    id: 8,
    url: "https://img.freepik.com/free-photo/herb-seeds-variety_23-2148463189.jpg",
    name: "Herb Seeds Variety Pack",
    price: 39,
    fakePrice: 55,
    offer: "29%",
    rating: 4.6,
    category: "Seeds",
    warranty: "No warranty; seeds are non-returnable.",
    inStock: true,
  },
  // Flower Bulbs
  {
    id: 9,
    url: "https://img.freepik.com/free-photo/flower-bulbs-scattered_23-2148435602.jpg",
    name: "Tulip Flower Bulbs",
    price: 89,
    fakePrice: 120,
    offer: "26%",
    rating: 4.8,
    category: "Flower Bulbs",
    warranty: "No warranty; bulbs are non-returnable.",
    inStock: true,
  },
  {
    id: 10,
    url: "https://img.freepik.com/free-photo/colorful-flower-bulbs-arranged_23-2148273589.jpg",
    name: "Daffodil Flower Bulbs",
    price: 75,
    fakePrice: 100,
    offer: "25%",
    rating: 4.6,
    category: "Flower Bulbs",
    warranty: "No warranty; bulbs are non-returnable.",
    inStock: true,
  },
  {
    id: 11,
    url: "https://img.freepik.com/free-photo/collection-of-lily-flower-bulbs_23-2148274567.jpg",
    name: "Lily Flower Bulbs",
    price: 95,
    fakePrice: 130,
    offer: "27%",
    rating: 4.7,
    category: "Flower Bulbs",
    warranty: "No warranty; bulbs are non-returnable.",
    inStock: true,
  },
  {
    id: 12,
    url: "https://img.freepik.com/free-photo/rose-flower-bulbs-assorted_23-2148247890.jpg",
    name: "Rose Flower Bulbs",
    price: 85,
    fakePrice: 115,
    offer: "26%",
    rating: 4.5,
    category: "Flower Bulbs",
    warranty: "No warranty; bulbs are non-returnable.",
    inStock: true,
  },
  // Pots
  {
    id: 13,
    url: "https://img.freepik.com/free-photo/clay-pots-arrangement_23-2148351270.jpg",
    name: "Clay Pot Set",
    price: 40,
    fakePrice: 50,
    offer: "20%",
    rating: 4.2,
    category: "Pots",
    warranty: "6-month warranty on pot durability.",
    inStock: true,
  },
  {
    id: 14,
    url: "https://img.freepik.com/free-photo/ceramic-plant-pots_23-2148311247.jpg",
    name: "Ceramic Plant Pot",
    price: 150,
    fakePrice: 180,
    offer: "17%",
    rating: 4.7,
    category: "Pots",
    warranty: "1-year warranty against breakage.",
    inStock: true,
  },
  {
    id: 15,
    url: "https://img.freepik.com/free-photo/metal-garden-pots_23-2148356890.jpg",
    name: "Metal Garden Pots",
    price: 110,
    fakePrice: 145,
    offer: "24%",
    rating: 4.4,
    category: "Pots",
    warranty: "1-year warranty on rust resistance.",
    inStock: true,
  },
  {
    id: 16,
    url: "https://img.freepik.com/free-photo/terracotta-pots_23-2148384567.jpg",
    name: "Terracotta Pots",
    price: 60,
    fakePrice: 80,
    offer: "25%",
    rating: 4.3,
    category: "Pots",
    warranty: "6-month warranty on pot condition.",
    inStock: true,
  },
  // Soil & Fertilizers
  {
    id: 17,
    url: "https://img.freepik.com/free-photo/soil-fertilizer-mix_23-2148234898.jpg",
    name: "Organic Soil Mix",
    price: 35,
    fakePrice: 45,
    offer: "22%",
    rating: 4.4,
    category: "Soil & Fertilizers",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 18,
    url: "https://img.freepik.com/free-photo/garden-fertilizer-bag_23-2148347895.jpg",
    name: "Garden Fertilizer",
    price: 70,
    fakePrice: 95,
    offer: "27%",
    rating: 4.5,
    category: "Soil & Fertilizers",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 19,
    url: "https://img.freepik.com/free-photo/compost-bag-garden-use_23-2148394567.jpg",
    name: "Compost Bag",
    price: 50,
    fakePrice: 70,
    offer: "29%",
    rating: 4.6,
    category: "Soil & Fertilizers",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 20,
    url: "https://img.freepik.com/free-photo/fertilizer-granules_23-2148446765.jpg",
    name: "Fertilizer Granules",
    price: 55,
    fakePrice: 75,
    offer: "27%",
    rating: 4.3,
    category: "Soil & Fertilizers",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  // Pebbles
  {
    id: 21,
    url: "https://img.freepik.com/free-photo/natural-pebbles-collection_23-2148245678.jpg",
    name: "Natural Garden Pebbles",
    price: 30,
    fakePrice: 50,
    offer: "40%",
    rating: 4.0,
    category: "Pebbles",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 22,
    url: "https://img.freepik.com/free-photo/colored-decorative-pebbles_23-2148267895.jpg",
    name: "Colored Decorative Pebbles",
    price: 55,
    fakePrice: 75,
    offer: "27%",
    rating: 4.6,
    category: "Pebbles",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 23,
    url: "https://img.freepik.com/free-photo/smooth-white-pebbles_23-2148367891.jpg",
    name: "Smooth White Pebbles",
    price: 40,
    fakePrice: 60,
    offer: "33%",
    rating: 4.2,
    category: "Pebbles",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 24,
    url: "https://img.freepik.com/free-photo/river-pebbles_23-2148478950.jpg",
    name: "River Pebbles",
    price: 35,
    fakePrice: 55,
    offer: "36%",
    rating: 4.1,
    category: "Pebbles",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  // Gifts
  {
    id: 25,
    url: "https://t4.ftcdn.net/jpg/05/26/89/27/240_F_526892749_TGePASLdg9uihUZtfquZpdGKD8FLTSTF.jpg",
    name: "Plant Gift Box Set",
    price: 120,
    fakePrice: 150,
    offer: "20%",
    rating: 4.8,
    category: "Gifts",
    warranty: "6-month warranty on plant health and gift set condition.",
    inStock: true,
  },
  {
    id: 26,
    url: "https://img.freepik.com/free-photo/mini-garden-kit-gift_23-2148234567.jpg",
    name: "Mini Garden Kit",
    price: 80,
    fakePrice: 100,
    offer: "20%",
    rating: 4.5,
    category: "Gifts",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 27,
    url: "https://img.freepik.com/free-photo/potted-plant-gift_23-2148234578.jpg",
    name: "Potted Plant Gift",
    price: 70,
    fakePrice: 90,
    offer: "22%",
    rating: 4.3,
    category: "Gifts",
    warranty: "6-month warranty on plant health.",
    inStock: true,
  },
  {
    id: 28,
    url: "https://img.freepik.com/free-photo/succulent-gift-box_23-2148234907.jpg",
    name: "Succulent Gift Box",
    price: 60,
    fakePrice: 75,
    offer: "20%",
    rating: 4.4,
    category: "Gifts",
    warranty: "6-month warranty on plant health and gift box.",
    inStock: true,
  },
  // Accessories
  {
    id: 29,
    url: "https://img.freepik.com/free-photo/gardening-tool-set_23-2148357890.jpg",
    name: "Gardening Tool Set",
    price: 50,
    fakePrice: 70,
    offer: "29%",
    rating: 4.7,
    category: "Accessories",
    warranty: "1-year warranty on tool set.",
    inStock: true,
  },
  {
    id: 30,
    url: "https://img.freepik.com/free-photo/watering-can-garden-use_23-2148237895.jpg",
    name: "Watering Can",
    price: 25,
    fakePrice: 35,
    offer: "28%",
    rating: 4.4,
    category: "Accessories",
    warranty: "6-month warranty on can durability.",
    inStock: true,
  },
  {
    id: 31,
    url: "https://img.freepik.com/free-photo/garden-gloves-pack_23-2148364567.jpg",
    name: "Garden Gloves Pack",
    price: 15,
    fakePrice: 25,
    offer: "40%",
    rating: 4.2,
    category: "Accessories",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  {
    id: 32,
    url: "https://img.freepik.com/free-photo/plant-labels-tags_23-2148234568.jpg",
    name: "Plant Labels and Tags",
    price: 10,
    fakePrice: 15,
    offer: "33%",
    rating: 4.0,
    category: "Accessories",
    warranty: "No warranty; non-returnable.",
    inStock: true,
  },
  // Offers & Blogs
  {
    id: 33,
    url: "https://img.freepik.com/free-photo/garden-maintenance-tips_23-2148345789.jpg",
    name: "Garden Maintenance Tips",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.9,
    category: "Offers",
    warranty: "No warranty applicable.",
    inStock: true,
  },
  {
    id: 34,
    url: "https://img.freepik.com/free-photo/diy-garden-projects_23-2148234890.jpg",
    name: "DIY Garden Projects",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.8,
    category: "Offers",
    warranty: "No warranty applicable.",
    inStock: true,
  },
  {
    id: 35,
    url: "https://img.freepik.com/free-photo/plants-care-guide_23-2148234789.jpg",
    name: "Plant Care Guide",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 5.0,
    category: "Offers",
    warranty: "No warranty applicable.",
    inStock: true,
  },
  {
    id: 36,
    url: "https://img.freepik.com/free-photo/seasonal-planting-guide_23-2148234568.jpg",
    name: "Seasonal Planting Guide",
    price: 0,
    fakePrice: 0,
    offer: "Free",
    rating: 4.7,
    category: "Offers",
    warranty: "No warranty applicable.",
    inStock: true,
  },
];

export default data;

export const navItems = [
  {
    name: "Products",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Seeds",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Flower Bulb",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Pots",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Soil & Fertilizer",
    list: [
      "Products",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Pebbles",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Gifts",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Accessories",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
  {
    name: "Offers",
    list: [
      "All Product",
      "Seeds",
      "Flower Bulbs",
      "Pots",
      "Soil & Fertilizers",
      "Pebbles",
      "Gifts",
      "Accessories",
      "Offers & Blogs",
    ],
  },
];
